development:
  adapter: postgresql
  encoding: unicode
  database: depot_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: depot_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: depot_production
  pool: 5
